/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/meta/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Seasons */
        get: operations["seasons_meta_seasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/leagues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Leagues */
        get: operations["leagues_meta_leagues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/leagues/known": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Leagues Known */
        get: operations["leagues_known_meta_leagues_known_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/leagues/big-five": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Leagues Big Five
         * @description Canonical Big 5 league names (same strings as in parquet `league`).
         */
        get: operations["leagues_big_five_meta_leagues_big_five_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Roles */
        get: operations["roles_meta_roles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/role-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Role Tokens
         * @description Wyscout position codes per tactical role (for sub-position filters in UI).
         */
        get: operations["role_tokens_meta_role_tokens_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Teams */
        get: operations["teams_meta_teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/players/top-performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Players Top Performance
         * @description Top players by performance index (paginated slice + total cohort size).
         */
        get: operations["players_top_performance_meta_players_top_performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Curated metrics present in parquet (legacy METRIC_COLS ∩ columns), with Raw/Per-90 hints.
         */
        get: operations["metrics_meta_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/game-areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Game Areas */
        get: operations["game_areas_meta_game_areas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Views */
        get: operations["views_meta_views_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_players_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{wyscout_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player Basic */
        get: operations["get_player_basic_players__wyscout_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{wyscout_id}/performance-index-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Performance Index History
         * @description Up to ``limit`` consecutive loaded seasons ending at ``season``, non-null PI rows only (chronological).
         *
         *     One row per season: the club with most minutes (same default as profile).
         */
        get: operations["performance_index_history_players__wyscout_id__performance_index_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{wyscout_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile */
        get: operations["profile_players__wyscout_id__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scatter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scatter */
        post: operations["scatter_scatter_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/screener": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Screener */
        post: operations["screener_screener_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{wyscout_id}/progression": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Progression */
        post: operations["progression_players__wyscout_id__progression_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/replacement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replacement */
        post: operations["replacement_replacement_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rankings */
        post: operations["rankings_rankings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bar */
        post: operations["bar_bar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bar/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bar Ranking */
        post: operations["bar_ranking_bar_ranking_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Translation */
        post: operations["translation_translation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/best-xi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Best Xi */
        post: operations["best_xi_teams_best_xi_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/minutes-distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Minutes Distribution */
        get: operations["minutes_distribution_teams_minutes_distribution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/potential": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Potential */
        post: operations["potential_potential_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/potential/cohort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Potential Cohort
         * @description Paginated age-cohort slice — ordered by ``potential_score`` desc, with total count.
         */
        post: operations["potential_cohort_potential_cohort_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BarPlayerSeries */
        BarPlayerSeries: {
            /** Wyscout Id */
            wyscout_id: number | null;
            /** Player */
            player: string;
            /** Club */
            club: string | null;
            /** League */
            league: string | null;
            /** Position */
            position: string | null;
            /** Minutes */
            minutes: number | null;
            /** Values */
            values: {
                [key: string]: number | null;
            };
        };
        /** BarRankingRequest */
        BarRankingRequest: {
            filters: components["schemas"]["PlayerFilters"];
            /** Metrics */
            metrics: string[];
            /** Modes */
            modes?: ("raw" | "p90" | "as_is")[];
            /**
             * Sort Combined
             * @description When true, order by sum of |m_i|/max_i over selected metrics in the filtered set (same scale as stacked bars). When false, use sort_by + sort_mode.
             * @default true
             */
            sort_combined: boolean;
            /**
             * Sort By
             * @description Ignored when sort_combined is true.
             * @default
             */
            sort_by: string;
            /**
             * Sort Mode
             * @default as_is
             * @enum {string}
             */
            sort_mode: "raw" | "p90" | "as_is";
            /**
             * Sort Desc
             * @default true
             */
            sort_desc: boolean;
            /**
             * Limit
             * @default 20
             */
            limit: number;
        };
        /** BarRankingResponse */
        BarRankingResponse: {
            /** Rows */
            rows: components["schemas"]["BarRankingRow"][];
            /** Metrics */
            metrics: string[];
            /** Labels */
            labels: {
                [key: string]: string;
            };
            /** Sort Combined */
            sort_combined: boolean;
            /** Sort By */
            sort_by: string;
            /**
             * Sort Mode
             * @enum {string}
             */
            sort_mode: "raw" | "p90" | "as_is";
            /** N */
            n: number;
            /**
             * Metric Max Abs
             * @description When combined sort ran: ABS max per metric over the filtered cohort — stacked-bar segment widths use this so they match ranking logic.
             */
            metric_max_abs?: {
                [key: string]: number;
            } | null;
        };
        /** BarRankingRow */
        BarRankingRow: {
            /** Rank */
            rank: number;
            /** Wyscout Id */
            wyscout_id: number | null;
            /** Player */
            player: string;
            /** Club */
            club: string | null;
            /** League */
            league: string | null;
            /** Position */
            position: string | null;
            /** Age */
            age: number | null;
            /** Minutes */
            minutes: number | null;
            /** Club Logo */
            club_logo?: string | null;
            /** Player Image Url */
            player_image_url?: string | null;
            /** Values */
            values: {
                [key: string]: number | null;
            };
        };
        /** BarRequest */
        BarRequest: {
            /** Season */
            season: number;
            /** Player Ids */
            player_ids: number[];
            /** Metrics */
            metrics: string[];
            /**
             * Mode
             * @default as_is
             * @enum {string}
             */
            mode: "raw" | "p90" | "as_is";
        };
        /** BarResponse */
        BarResponse: {
            /** Metrics */
            metrics: string[];
            /** Labels */
            labels: {
                [key: string]: string;
            };
            /** Players */
            players: components["schemas"]["BarPlayerSeries"][];
        };
        /** BestXIPlayer */
        BestXIPlayer: {
            /** Slot */
            slot: string;
            /** Player */
            player: string;
            /** Wyscout Id */
            wyscout_id?: number | null;
            /** Club */
            club?: string | null;
            /** Club Logo */
            club_logo?: string | null;
            /** League */
            league?: string | null;
            /** Position */
            position?: string | null;
            /** Age */
            age?: number | null;
            /** Minutes */
            minutes?: number | null;
            /** Goals */
            goals?: number | null;
            /** Assists */
            assists?: number | null;
            /** Performance Index */
            performance_index?: number | null;
            /** Position Type */
            position_type: string;
            /** Player Image Url */
            player_image_url?: string | null;
        };
        /** BestXIRequest */
        BestXIRequest: {
            filters: components["schemas"]["PlayerFilters"];
            /**
             * Formation
             * @default 4-3-3
             */
            formation: string;
            /**
             * Mode
             * @default by_league
             * @enum {string}
             */
            mode: "by_league" | "by_club" | "two_teams";
            /** Club */
            club?: string | null;
            /** Team2 */
            team2?: string | null;
        };
        /** BestXIResponse */
        BestXIResponse: {
            /** Formation */
            formation: string;
            /** Context */
            context: string;
            /** Slots */
            slots: components["schemas"]["BestXIPlayer"][];
            /** Top3 */
            top3: components["schemas"]["BestXITop3Row"][];
            /** Coords */
            coords: {
                [key: string]: number[];
            };
        };
        /** BestXITop3Row */
        BestXITop3Row: {
            /** Slot */
            slot: string;
            /** Rank */
            rank: number;
            /** Player */
            player: string;
            /** Wyscout Id */
            wyscout_id?: number | null;
            /** Club */
            club?: string | null;
            /** Club Logo */
            club_logo?: string | null;
            /** Age */
            age?: number | null;
            /** Minutes */
            minutes?: number | null;
            /** Performance Index */
            performance_index?: number | null;
            /** Position Type */
            position_type: string;
            /** Player Image Url */
            player_image_url?: string | null;
        };
        /** GameAreaProfileBlock */
        GameAreaProfileBlock: {
            /** Area */
            area: string;
            index: components["schemas"]["ProfileMetric"];
            /** Metrics */
            metrics: components["schemas"]["ProfileMetric"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LeagueStyleFitRow
         * @description Cosine similarity of player style vs minutes-weighted league centroid (see legacy League Style Fit).
         */
        LeagueStyleFitRow: {
            /** League */
            league: string;
            /** N Teams */
            n_teams: number;
            /**
             * Style Fit
             * @description Cosine similarity in z-scored style space (higher = closer fit).
             */
            style_fit: number;
        };
        /** MetricOption */
        MetricOption: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /**
             * Supports Mode
             * @default false
             */
            supports_mode: boolean;
            /**
             * Default Mode
             * @default as_is
             * @enum {string}
             */
            default_mode: "raw" | "p90" | "as_is";
        };
        /** MinutesDistributionPlayer */
        MinutesDistributionPlayer: {
            /** Wyscout Id */
            wyscout_id?: number | null;
            /** Player */
            player: string;
            /** Player Image Url */
            player_image_url?: string | null;
            /** Position */
            position?: string | null;
            /** Age */
            age?: number | null;
            /** Minutes */
            minutes: number;
            /** Matches */
            matches?: number | null;
            /** League Minutes Pct */
            league_minutes_pct: number;
            /**
             * Age Zone
             * @enum {string}
             */
            age_zone: "young" | "prime" | "veteran";
        };
        /**
         * MinutesDistributionResponse
         * @description Squad minutes distribution for a single club in a single season.
         *
         *     `max_league_minutes = max_league_games * 90` from the static
         *     `LEAGUE_MAX_GAMES` table in `core/config.py`. Multi-stage / playoff leagues
         *     use the regular-season game count; downstream callers clamp the per-player
         *     pct to 100 in case a player accrues playoff minutes on top.
         */
        MinutesDistributionResponse: {
            /** Club */
            club: string;
            /** Club Logo */
            club_logo?: string | null;
            /** League */
            league?: string | null;
            /** Season */
            season: number;
            /** Max League Games */
            max_league_games: number;
            /** Max League Minutes */
            max_league_minutes: number;
            /** Young Max Age */
            young_max_age: number;
            /** Prime Max Age */
            prime_max_age: number;
            /** Players */
            players: components["schemas"]["MinutesDistributionPlayer"][];
        };
        /**
         * PerformanceIndexHistoryPoint
         * @description Single season snapshot for scout profile PI progression (club = dominant minutes row).
         */
        PerformanceIndexHistoryPoint: {
            /** Season */
            season: number;
            /** Performance Index */
            performance_index: number;
            /** Club */
            club?: string | null;
            /** Club Logo */
            club_logo?: string | null;
        };
        /**
         * PerformanceIndexHistoryResponse
         * @description Chronological (oldest → newest), at most ``limit`` seasons with non-null PI.
         */
        PerformanceIndexHistoryResponse: {
            /** Points */
            points: components["schemas"]["PerformanceIndexHistoryPoint"][];
        };
        /** PlayerFilters */
        PlayerFilters: {
            /**
             * Season
             * @description Season start year, e.g. 2025 for 25-26
             */
            season: number;
            /** Leagues */
            leagues?: string[] | null;
            /** Roles */
            roles?: string[] | null;
            /** Teams */
            teams?: string[] | null;
            /** Age Min */
            age_min?: number | null;
            /** Age Max */
            age_max?: number | null;
            /** Minutes Min */
            minutes_min?: number | null;
            /** Minutes Max */
            minutes_max?: number | null;
            /** Market Value Max */
            market_value_max?: number | null;
            /** Foot */
            foot?: string | null;
            /** Contract Expires Year Min */
            contract_expires_year_min?: number | null;
            /** Contract Expires Year Max */
            contract_expires_year_max?: number | null;
        };
        /** PlayerListItem */
        PlayerListItem: {
            /** Wyscout Id */
            wyscout_id?: number | null;
            /** Player */
            player: string;
            /** Full Name */
            full_name?: string | null;
            /** Club */
            club?: string | null;
            /** League */
            league?: string | null;
            /** Position */
            position?: string | null;
            /** Age */
            age?: number | null;
            /** Minutes */
            minutes?: number | null;
            /** Market Value */
            market_value?: number | null;
        };
        /** PlayerProfile */
        PlayerProfile: {
            /** Wyscout Id */
            wyscout_id: number | null;
            /** Player */
            player: string;
            /** Full Name */
            full_name: string | null;
            /** Club */
            club: string | null;
            /** League */
            league: string | null;
            /** Club Logo */
            club_logo?: string | null;
            /** Position */
            position: string | null;
            /** Age */
            age: number | null;
            /** Minutes */
            minutes: number | null;
            /** Market Value */
            market_value: number | null;
            /** Foot */
            foot: string | null;
            /** Height */
            height: number | null;
            /** Role */
            role: string | null;
            /** Radar */
            radar: components["schemas"]["ProfileMetric"][];
            /** Table */
            table: components["schemas"]["ProfileMetric"][];
            /** Performance Index */
            performance_index: number | null;
            /** Performance Index Percentile */
            performance_index_percentile?: number | null;
            /** Games */
            games?: number | null;
            /** Goals */
            goals?: number | null;
            /** Assists */
            assists?: number | null;
            /**
             * Player Image Url
             * @description HTTPS headshot URL (Transfermarkt CDN or Wyscout image when enriched in parquet)
             */
            player_image_url?: string | null;
            /** Position Tokens */
            position_tokens?: string[];
            /** Position Tokens Primary */
            position_tokens_primary?: string[];
            /** Position Tokens Secondary */
            position_tokens_secondary?: string[];
            /** Game Areas */
            game_areas?: components["schemas"]["GameAreaProfileBlock"][];
            /** Traits */
            traits?: components["schemas"]["PlayerTrait"][];
            /**
             * Clubs In Season
             * @description All (club, minutes) rows for this wyscout_id in the season — surface a switcher when length > 1.
             */
            clubs_in_season?: components["schemas"]["ProfileClubStint"][];
            /**
             * Performance Index History
             * @description Filled when GET /players/{wyscout_id}/profile sets performance_index_history_limit (mini PI trajectory).
             */
            performance_index_history?: components["schemas"]["PerformanceIndexHistoryPoint"][] | null;
        };
        /** PlayerTrait */
        PlayerTrait: {
            /** Positive */
            positive: boolean;
            /** Label */
            label: string;
            /** Game Area */
            game_area: string;
        };
        /**
         * PotentialCohortRequest
         * @description Single age-cohort slice for the Potential big-board (paginated).
         */
        PotentialCohortRequest: {
            filters: components["schemas"]["PlayerFilters"];
            /** Age */
            age: number;
            /**
             * Limit
             * @default 20
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /** PotentialCohortResponse */
        PotentialCohortResponse: {
            /** Age */
            age: number;
            /** Players */
            players: components["schemas"]["PotentialPlayer"][];
            /** Total */
            total: number;
        };
        /** PotentialPlayer */
        PotentialPlayer: {
            /** Wyscout Id */
            wyscout_id: number | null;
            /** Player */
            player: string;
            /** Club */
            club?: string | null;
            /** Club Logo */
            club_logo?: string | null;
            /** League */
            league?: string | null;
            /** Position */
            position?: string | null;
            /** Age */
            age?: number | null;
            /** Minutes */
            minutes?: number | null;
            /** Current Pi */
            current_pi?: number | null;
            /** Potential Score */
            potential_score: number;
            /** Player Image Url */
            player_image_url?: string | null;
        };
        /** PotentialRequest */
        PotentialRequest: {
            filters: components["schemas"]["PlayerFilters"];
        };
        /** PotentialResponse */
        PotentialResponse: {
            /** Players */
            players: components["schemas"]["PotentialPlayer"][];
            /** N */
            n: number;
        };
        /** ProfileClubStint */
        ProfileClubStint: {
            /** Club */
            club: string;
            /** Minutes */
            minutes?: number | null;
            /** Club Logo */
            club_logo?: string | null;
        };
        /** ProfileMetric */
        ProfileMetric: {
            /** Metric */
            metric: string;
            /** Label */
            label: string;
            /** Value */
            value: number | null;
            /** Percentile */
            percentile: number | null;
        };
        /** ProgressionMetricSeries */
        ProgressionMetricSeries: {
            /** Metric */
            metric: string;
            /** Label */
            label: string;
            /** Points */
            points: components["schemas"]["ProgressionPoint"][];
        };
        /** ProgressionPoint */
        ProgressionPoint: {
            /** Season */
            season: number;
            /** Value */
            value: number | null;
            /** Club */
            club?: string | null;
            /** League */
            league?: string | null;
            /** Minutes */
            minutes?: number | null;
            /** Club Logo */
            club_logo?: string | null;
        };
        /** ProgressionRequest */
        ProgressionRequest: {
            /** Metrics */
            metrics: string[];
            /** Target Season */
            target_season: number;
            /**
             * Seasons Count
             * @default 5
             */
            seasons_count: number;
            /**
             * Mode
             * @default as_is
             * @enum {string}
             */
            mode: "raw" | "p90" | "as_is";
        };
        /** ProgressionResponse */
        ProgressionResponse: {
            /** Player */
            player: string | null;
            /** Metrics */
            metrics: components["schemas"]["ProgressionMetricSeries"][];
            /** Seasons */
            seasons: number[];
        };
        /** RankingsRequest */
        RankingsRequest: {
            filters: components["schemas"]["PlayerFilters"];
            /** Metric */
            metric: string;
            /**
             * Mode
             * @default as_is
             * @enum {string}
             */
            mode: "raw" | "p90" | "as_is";
            /**
             * Desc
             * @default true
             */
            desc: boolean;
            /**
             * Limit
             * @default 50
             */
            limit: number;
        };
        /** RankingsResponse */
        RankingsResponse: {
            /** Rows */
            rows: components["schemas"]["RankingsRow"][];
            /** Metric */
            metric: string;
            /** Label */
            label: string;
            /** N */
            n: number;
        };
        /** RankingsRow */
        RankingsRow: {
            /** Rank */
            rank: number;
            /** Wyscout Id */
            wyscout_id: number | null;
            /** Player */
            player: string;
            /** Club */
            club: string | null;
            /** League */
            league: string | null;
            /** Position */
            position: string | null;
            /** Age */
            age: number | null;
            /** Minutes */
            minutes: number | null;
            /** Club Logo */
            club_logo?: string | null;
            /** Value */
            value: number | null;
        };
        /** ReplacementCandidate */
        ReplacementCandidate: {
            /** Wyscout Id */
            wyscout_id: number | null;
            /** Player */
            player: string;
            /** Club */
            club: string | null;
            /** League */
            league: string | null;
            /** Position */
            position: string | null;
            /** Age */
            age: number | null;
            /** Minutes */
            minutes: number | null;
            /** Similarity */
            similarity: number;
            /** Candidate Season */
            candidate_season?: number | null;
            /** Club Logo */
            club_logo?: string | null;
            /** Player Image Url */
            player_image_url?: string | null;
        };
        /** ReplacementRequest */
        ReplacementRequest: {
            /** Target Player Id */
            target_player_id: number;
            /** Target Season */
            target_season: number;
            /** Candidate Seasons */
            candidate_seasons: number[];
            candidate_filters: components["schemas"]["PlayerFilters"];
            /**
             * Limit
             * @default 20
             */
            limit: number;
        };
        /** ReplacementResponse */
        ReplacementResponse: {
            target: components["schemas"]["ReplacementCandidate"] | null;
            /** Candidates */
            candidates: components["schemas"]["ReplacementCandidate"][];
            /** N */
            n: number;
            /**
             * Profile
             * @enum {string}
             */
            profile: "indices" | "per90" | "combined";
            /**
             * Method
             * @enum {string}
             */
            method: "cosine" | "euclidean";
        };
        /** ScatterPoint */
        ScatterPoint: {
            /** Wyscout Id */
            wyscout_id: number | null;
            /** Player */
            player: string;
            /** Club */
            club: string | null;
            /** League */
            league: string | null;
            /** Position */
            position: string | null;
            /** Age */
            age: number | null;
            /** Minutes */
            minutes: number | null;
            /** X */
            x: number | null;
            /** Y */
            y: number | null;
            /** Size */
            size?: number | null;
            /** Player Image Url */
            player_image_url?: string | null;
        };
        /** ScatterRequest */
        ScatterRequest: {
            filters: components["schemas"]["PlayerFilters"];
            /** X Metric */
            x_metric: string;
            /** Y Metric */
            y_metric: string;
            /**
             * X Mode
             * @default as_is
             * @enum {string}
             */
            x_mode: "raw" | "p90" | "as_is";
            /**
             * Y Mode
             * @default as_is
             * @enum {string}
             */
            y_mode: "raw" | "p90" | "as_is";
            /** Size Metric */
            size_metric?: string | null;
            /** Label Metric */
            label_metric?: string | null;
            /** Highlight Player Ids */
            highlight_player_ids?: number[];
        };
        /** ScatterResponse */
        ScatterResponse: {
            /** Points */
            points: components["schemas"]["ScatterPoint"][];
            /** X Metric */
            x_metric: string;
            /** Y Metric */
            y_metric: string;
            /** X Label */
            x_label: string;
            /** Y Label */
            y_label: string;
            /** Size Metric */
            size_metric: string | null;
            /** N */
            n: number;
        };
        /** ScreenerCriterion */
        ScreenerCriterion: {
            /** Metric */
            metric: string;
            /**
             * Mode
             * @default as_is
             * @enum {string}
             */
            mode: "raw" | "p90" | "as_is";
            /** Operator */
            operator: string;
            /** Value */
            value: number;
        };
        /** ScreenerRequest */
        ScreenerRequest: {
            filters: components["schemas"]["PlayerFilters"];
            /** Criteria */
            criteria?: components["schemas"]["ScreenerCriterion"][];
            /** Sort By */
            sort_by?: string | null;
            /**
             * Sort Mode
             * @default as_is
             * @enum {string}
             */
            sort_mode: "raw" | "p90" | "as_is";
            /**
             * Sort Desc
             * @default true
             */
            sort_desc: boolean;
            /**
             * Limit
             * @default 20
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /** ScreenerResponse */
        ScreenerResponse: {
            /** Rows */
            rows: components["schemas"]["ScreenerRow"][];
            /** Total */
            total: number;
        };
        /** ScreenerRow */
        ScreenerRow: {
            /** Wyscout Id */
            wyscout_id: number | null;
            /** Club Logo */
            club_logo?: string | null;
            /** Player */
            player: string;
            /** Club */
            club: string | null;
            /** League */
            league: string | null;
            /** Position */
            position: string | null;
            /** Age */
            age: number | null;
            /** Minutes */
            minutes: number | null;
            /** Metrics */
            metrics: {
                [key: string]: number | null;
            };
        };
        /** StrengthAdjustment */
        StrengthAdjustment: {
            /** Value */
            value: number;
            /** Xg Factor */
            xg_factor: number;
            /** Tier Factor */
            tier_factor: number;
            /** League Factor */
            league_factor: number;
            /** Raw Team Xg P90 */
            raw_team_xg_p90?: number | null;
            /** Raw League Avg Xg P90 */
            raw_league_avg_xg_p90?: number | null;
            /**
             * Dominance Z
             * @default 0
             */
            dominance_z: number;
            /**
             * Available
             * @default false
             */
            available: boolean;
            /**
             * Clamped
             * @default false
             */
            clamped: boolean;
        };
        /**
         * TopPerformancePage
         * @description Paged slice of leaderboard + total eligible players (distinct Wyscout IDs).
         */
        TopPerformancePage: {
            /** Items */
            items: components["schemas"]["TopPerformancePlayer"][];
            /** Total */
            total: number;
        };
        /** TopPerformancePlayer */
        TopPerformancePlayer: {
            /** Wyscout Id */
            wyscout_id?: number | null;
            /** Player */
            player: string;
            /** Club */
            club?: string | null;
            /** League */
            league?: string | null;
            /** Position */
            position?: string | null;
            /** Age */
            age?: number | null;
            /** Minutes */
            minutes?: number | null;
            /** Performance Index */
            performance_index?: number | null;
            /** Club Logo */
            club_logo?: string | null;
            /** Player Image Url */
            player_image_url?: string | null;
            /** Distribution Index */
            distribution_index?: number | null;
            /** Take Ons Index */
            take_ons_index?: number | null;
            /** Assistance Index */
            assistance_index?: number | null;
            /** Finishing Index */
            finishing_index?: number | null;
            /** Aerial Play Index */
            aerial_play_index?: number | null;
            /** Ground Defense Index */
            ground_defense_index?: number | null;
        };
        /** TranslationLeaguePool */
        TranslationLeaguePool: {
            /** League */
            league: string;
            /** N */
            n: number;
            /** Mu */
            mu: number | null;
            /** Sigma */
            sigma: number | null;
            /** Peers */
            peers: components["schemas"]["TranslationPeer"][];
            /** Projected Perf Index */
            projected_perf_index: number | null;
            /** Projected Z Score */
            projected_z_score: number | null;
            /** Projected Color */
            projected_color?: string | null;
            /** Power */
            power: number | null;
            /**
             * Insufficient Data
             * @default false
             */
            insufficient_data: boolean;
        };
        /** TranslationPeer */
        TranslationPeer: {
            /** Wyscout Id */
            wyscout_id: number | null;
            /** Player */
            player: string;
            /** Club */
            club: string | null;
            /** Age */
            age: number | null;
            /** Perf Index */
            perf_index: number;
            /** Z Score */
            z_score: number;
            /** Color */
            color: string;
            /** Player Image Url */
            player_image_url?: string | null;
        };
        /** TranslationRequest */
        TranslationRequest: {
            /** Player Id */
            player_id: number;
            /** Season */
            season: number;
            /** Target Season */
            target_season?: number | null;
            /** Target Leagues */
            target_leagues?: string[] | null;
            /** Min Minutes */
            min_minutes?: number | null;
        };
        /** TranslationResponse */
        TranslationResponse: {
            /** Player */
            player: string;
            /** Club */
            club: string | null;
            /** Source League */
            source_league: string;
            /** Source Power */
            source_power: number | null;
            /** Source Perf Index */
            source_perf_index: number;
            source_strength_adj: components["schemas"]["StrengthAdjustment"];
            /** Role */
            role: string;
            /** Player Age */
            player_age: number | null;
            /** Season */
            season: number;
            /** Target Season */
            target_season: number;
            /** Min Minutes */
            min_minutes: number;
            /** Pools */
            pools: components["schemas"]["TranslationLeaguePool"][];
            /** Target Leagues */
            target_leagues: string[];
            /** League Style Fit */
            league_style_fit?: components["schemas"]["LeagueStyleFitRow"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    seasons_meta_seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number[];
                };
            };
        };
    };
    leagues_meta_leagues_get: {
        parameters: {
            query?: {
                season?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leagues_known_meta_leagues_known_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    leagues_big_five_meta_leagues_big_five_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    roles_meta_roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    role_tokens_meta_role_tokens_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    teams_meta_teams_get: {
        parameters: {
            query: {
                season: number;
                league?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    players_top_performance_meta_players_top_performance_get: {
        parameters: {
            query: {
                /** @description Season start year */
                season: number;
                /** @description Minimum minutes played */
                minutes_min?: number;
                limit?: number;
                /** @description Paging offset */
                offset?: number;
                /** @description Filter by leagues */
                leagues?: string[] | null;
                /** @description Filter by tactical roles */
                roles?: string[] | null;
                age_min?: number | null;
                age_max?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopPerformancePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_meta_metrics_get: {
        parameters: {
            query: {
                season: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricOption"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    game_areas_meta_game_areas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    views_meta_views_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    search_players_search_get: {
        parameters: {
            query: {
                /** @description Season start year */
                season: number;
                /** @description Free text query — accent/case insensitive */
                q?: string;
                league?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_basic_players__wyscout_id__get: {
        parameters: {
            query: {
                season: number;
            };
            header?: never;
            path: {
                wyscout_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    performance_index_history_players__wyscout_id__performance_index_history_get: {
        parameters: {
            query: {
                /** @description Anchor season (inclusive) — last N loaded seasons up to this year. */
                season: number;
                limit?: number;
            };
            header?: never;
            path: {
                wyscout_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceIndexHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_players__wyscout_id__profile_get: {
        parameters: {
            query: {
                season: number;
                /** @description Disambiguates when a player has rows for multiple clubs in the same season. */
                club?: string | null;
                /** @description Percentile cohort league; omit to use this player's league */
                league?: string | null;
                min_minutes?: number;
                /** @description When set, include up to N PI trajectory seasons inside this response. */
                performance_index_history_limit?: number | null;
            };
            header?: never;
            path: {
                wyscout_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scatter_scatter_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScatterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScatterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    screener_screener_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreenerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    progression_players__wyscout_id__progression_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wyscout_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgressionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replacement_replacement_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplacementRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplacementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rankings_rankings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RankingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bar_bar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BarRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bar_ranking_bar_ranking_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BarRankingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarRankingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    translation_translation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    best_xi_teams_best_xi_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BestXIRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BestXIResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    minutes_distribution_teams_minutes_distribution_get: {
        parameters: {
            query: {
                /** @description Season start year (e.g. 2025 for 25-26) */
                season: number;
                /** @description Club name as stored in parquet `club` */
                club: string;
                /** @description Inclusive max age for the 'young' band */
                young_max?: number;
                /** @description Inclusive max age for the 'prime' band */
                prime_max?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MinutesDistributionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    potential_potential_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PotentialRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PotentialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    potential_cohort_potential_cohort_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PotentialCohortRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PotentialCohortResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
